name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run check
      env:
        API_KEY: ${{ secrets.CLAUDE_API_KEY }}
      run: make check

